name: CI - API Bin Packing

on:
  push:
    branches: ["CI"]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: binpacking:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true  # <- garante que a imagem estará disponível para docker run

      - name: Executar fluxo completo e validações
        continue-on-error: true
        run: |
          docker run -d --name fastapi-app -p 8000:8000 -v ${{ github.workspace }}/data:/app/data binpacking uvicorn src.main:app --host 0.0.0.0 --port 8000
          sleep 5
          docker exec fastapi-app python3 test/teste_input.py

      - name: Validação Camiseta
        run: |
          docker exec fastapi-app python3 test/validacao_camiseta.py

      - name: Validação Tempo
        run: |
          docker exec fastapi-app python3 test/validacao_tempo.py

      - name: Validação Espaço da Mesa
        run: |
          docker exec fastapi-app python3 test/validacao_espaco.py

      - name: Stop container
        if: always()
        run: docker stop fastapi-app
